// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = { treeSitterCacheSize: number, lspMaxMessageSizeMb: number, watcherDebounceMs: number, lspDidChangeDebounceMs: number, diagnosticsPullDelayMs: number, hoverDelayMs: number, navigationHistoryDepth: number, recentFilesLimit: number, 
/**
 * Number of days to retain log files in ~/.keynobi/logs/ (default: 7).
 */
logRetentionDays: number, 
/**
 * Max total size of ~/.keynobi/logs/ in MB before size-based rotation triggers (default: 500).
 */
logMaxSizeMb: number, };
