// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = { treeSitterCacheSize: number, lspMaxMessageSizeMb: number, watcherDebounceMs: number, lspDidChangeDebounceMs: number, diagnosticsPullDelayMs: number, hoverDelayMs: number, navigationHistoryDepth: number, recentFilesLimit: number, };
