// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the skill is installed for Claude Code.
 */
export type AgentSkillState = "notInstalled" | "installed" | "different";
