// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSkillState } from "./AgentSkillState";

/**
 * The Keynobi agent skill and its Claude Code installation.
 */
export type AgentSkillStatus = { 
/**
 * Where the skill is installed for Claude Code (user scope).
 */
path: string, state: AgentSkillState, 
/**
 * The `SKILL.md` that installing writes.
 */
content: string, 
/**
 * The MCP resource that serves the same file to any client.
 */
resourceUri: string, };
