// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The MCP client behind a [`BuildActor::Agent`].
 */
export type AgentActor = { 
/**
 * The app's id for an attached session; `None` for a standalone server.
 */
sessionId: number | null, 
/**
 * The client's name from its `initialize` request, when known.
 */
clientName: string | null, 
/**
 * A standalone `keynobi --mcp` process rather than a session attached to the app.
 */
standalone: boolean, };
