// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppExitReason } from "./AppExitReason";

/**
 * One recorded process exit (`dumpsys activity exit-info`).
 */
export type AppExitRecord = { 
/**
 * When the process exited, as the device printed it (device local time).
 */
timestamp: string | null, 
/**
 * The same time as ISO 8601 (`2024-05-02T10:15:03.482`), when the device
 * printed a date and time Keynobi can read. It has no offset: the dump
 * does not say which time zone the device uses.
 */
timestampLocal: string | null, pid: number | null, processName: string | null, reason: AppExitReason, 
/**
 * The raw `REASON_*` code.
 */
reasonCode: number | null, 
/**
 * The device's name for the reason, for example `APP CRASH(EXCEPTION)`.
 */
reasonLabel: string | null, subReasonCode: number | null, 
/**
 * The device's name for the sub-reason, for example `TOO MANY CACHED`.
 */
subReason: string | null, 
/**
 * The exit code for `exitSelf`, the signal for `signaled` and `crashNative`.
 */
status: number | null, 
/**
 * `RunningAppProcessInfo` importance when the process died (100 = foreground).
 */
importance: number | null, 
/**
 * A name for `importance`, for example `foreground` or `cached`.
 */
importanceName: string | null, 
/**
 * Last proportional set size in KB (rounded by the device).
 */
pssKb: number | null, 
/**
 * Last resident set size in KB (rounded by the device).
 */
rssKb: number | null, 
/**
 * The system's description, capped at `MAX_EXIT_DESCRIPTION_CHARS`.
 */
description: string | null, };
