// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a process exited, as Android records it (`ApplicationExitInfo.REASON_*`).
 */
export type AppExitReason = "unknown" | "exitSelf" | "signaled" | "lowMemory" | "crash" | "crashNative" | "anr" | "initializationFailure" | "permissionChange" | "excessiveResourceUsage" | "userRequested" | "userStopped" | "dependencyDied" | "other" | "freezer" | "packageStateChange" | "packageUpdated";
