// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppExitRecord } from "./AppExitRecord";

/**
 * The exit history of one package on one device.
 */
export type AppExitReasons = { serial: string, package: string, 
/**
 * The device's API level, when it reported one.
 */
apiLevel: number | null, 
/**
 * False when the device cannot report exit reasons (below Android 11).
 */
supported: boolean, 
/**
 * Why no records are listed, when none are.
 */
message: string | null, 
/**
 * Newest first, at most `MAX_EXIT_RECORDS`.
 */
records: Array<AppExitRecord>, 
/**
 * How many records the device reported, before the cap.
 */
totalRecords: number, };
