// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured error type returned by Tauri command handlers at the IPC boundary.
 *
 * Serializes as `{"kind": "notFound", "message": "..."}` so the TypeScript
 * frontend can match on the `kind` field and show context-appropriate messages.
 */
export type AppError = { "kind": "notFound", "message": string } | { "kind": "permissionDenied", "message": string } | { "kind": "invalidInput", "message": string } | { "kind": "io", "message": string } | { "kind": "processFailed", "message": string } | { "kind": "settingsError", "message": string } | { "kind": "mcpError", "message": string } | { "kind": "other", "message": string };
