// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { AndroidSettings } from "./AndroidSettings";
import type { AppearanceSettings } from "./AppearanceSettings";
import type { BuildSettings } from "./BuildSettings";
import type { EditorSettings } from "./EditorSettings";
import type { JavaSettings } from "./JavaSettings";
import type { LogcatSettings } from "./LogcatSettings";
import type { LspSettings } from "./LspSettings";
import type { McpSettings } from "./McpSettings";
import type { ProjectEntry } from "./ProjectEntry";
import type { SearchSettings } from "./SearchSettings";

/**
 * All app settings persisted to `~/.keynobi/settings.json`.
 * Every field uses `#[serde(default)]` so the file is forward-compatible —
 * adding new settings never breaks existing config files.
 */
export type AppSettings = { editor: EditorSettings, appearance: AppearanceSettings, search: SearchSettings, android: AndroidSettings, lsp: LspSettings, java: JavaSettings, advanced: AdvancedSettings, build: BuildSettings, logcat: LogcatSettings, mcp: McpSettings, 
/**
 * Registry of recently-opened projects.  Capped at 20 entries; oldest
 * non-pinned entry is evicted when the cap is exceeded.
 */
recentProjects: Array<ProjectEntry>, 
/**
 * The path of the project that was active when the app was last closed.
 */
lastActiveProject: string | null, };
