// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { AndroidSettings } from "./AndroidSettings";
import type { AppearanceSettings } from "./AppearanceSettings";
import type { BuildSettings } from "./BuildSettings";
import type { EditorSettings } from "./EditorSettings";
import type { FilesSettings } from "./FilesSettings";
import type { JavaSettings } from "./JavaSettings";
import type { LogcatSettings } from "./LogcatSettings";
import type { LspSettings } from "./LspSettings";
import type { SearchSettings } from "./SearchSettings";

/**
 * All IDE settings persisted to `~/.androidide/settings.json`.
 * Every field uses `#[serde(default)]` so the file is forward-compatible —
 * adding new settings never breaks existing config files.
 */
export type AppSettings = { editor: EditorSettings, appearance: AppearanceSettings, search: SearchSettings, files: FilesSettings, android: AndroidSettings, lsp: LspSettings, java: JavaSettings, advanced: AdvancedSettings, build: BuildSettings, logcat: LogcatSettings, };
