// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An Android system image available for download via `sdkmanager`.
 */
export type AvailableSystemImage = { 
/**
 * Full SDK package ID (e.g. `"system-images;android-35;google_apis;arm64-v8a"`).
 */
sdkId: string, 
/**
 * Android API level.
 */
apiLevel: number, 
/**
 * Image variant (e.g. `"google_apis"`, `"google_apis_playstore"`, `"default"`).
 */
variant: string, 
/**
 * CPU ABI (e.g. `"arm64-v8a"`, `"x86_64"`).
 */
abi: string, 
/**
 * Human-friendly label.
 */
displayName: string, 
/**
 * Whether the image is already installed locally.
 */
installed: boolean, };
