// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about an Android Virtual Device.
 */
export type AvdInfo = { 
/**
 * AVD name used with `emulator @<name>`.
 */
name: string, 
/**
 * Friendly display name from the AVD ini file.
 */
displayName: string, 
/**
 * Android target (e.g. `android-35`).
 */
target: string | null, apiLevel: number | null, 
/**
 * ABI type (e.g. `arm64-v8a`, `x86_64`).
 */
abi: string | null, 
/**
 * Path to the AVD directory.
 */
path: string, };
