// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildFileHash } from "./BuildFileHash";

/**
 * Where a build came from, recorded when it finished, so two builds can be
 * compared: the git commit checked out and the SHA-256 of its build files.
 */
export type BuildProvenance = { 
/**
 * The commit checked out (`HEAD`), full hex; `None` when git could not
 * say (see `gitUnavailable`) or before the first commit.
 */
commit: string | null, 
/**
 * The branch checked out; `None` when `HEAD` is detached or unknown.
 */
branch: string | null, 
/**
 * Whether files differed from the commit (untracked files included);
 * `None` when unknown.
 */
dirty: boolean | null, 
/**
 * How many files differed, when known.
 */
changedFiles: number | null, 
/**
 * Why git gave nothing: not found, not a repository, or failed.
 */
gitUnavailable: string | null, 
/**
 * The build files found, by path relative to the Gradle root, sorted.
 */
buildFiles: Array<BuildFileHash>, 
/**
 * From the Gradle wrapper's `distributionUrl` (`8.7`).
 */
gradleVersion: string | null, 
/**
 * `JAVA_VERSION` of the JDK Gradle builds with (`17.0.9`).
 */
jdkVersion: string | null, };
