// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";

/**
 * Payload of `build:started`, emitted for every build the app's process runs.
 */
export type BuildStartedEvent = { 
/**
 * The run's ID (its Gradle process ID), shared by `build:lines` and `build:complete`.
 */
runId: number, task: string, origin: BuildActor, startedAt: string, projectRoot: string | null, };
