// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single discoverable Gradle build variant.
 */
export type BuildVariant = { 
/**
 * Variant name as used in Gradle tasks (e.g. `freeDebug`, `release`).
 */
name: string, 
/**
 * Build type component (e.g. `debug`, `release`).
 */
buildType: string, 
/**
 * Product flavor components, if any (e.g. `["free"]`).
 */
flavors: Array<string>, 
/**
 * Gradle assemble task (e.g. `assembleFreeDebug`).
 */
assembleTask: string, 
/**
 * Gradle install task (e.g. `installFreeDebug`).
 */
installTask: string, };
