// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a completed build.
 */
export type BuildResult = { success: boolean, durationMs: bigint, errorCount: number, warningCount: number, };
