// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentActor } from "./AgentActor";

/**
 * Who started or cancelled a build.
 */
export type BuildActor = { "kind": "app" } | { "kind": "appQuit" } | { "kind": "agent" } & AgentActor;
