// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";

/**
 * Payload of `build:complete`, emitted when a build finishes, fails, or is cancelled.
 */
export type BuildCompleteEvent = { 
/**
 * The run this event belongs to (the Gradle process ID the build started with).
 */
runId: number, success: boolean, cancelled: boolean, durationMs: number, errorCount: number, warningCount: number, task: string, origin: BuildActor | null, cancelledBy: BuildActor | null, };
