// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build system settings: auto-deploy behaviour, last-used selections.
 * Gradle JVM/parallel/offline flags are configured in Android Studio / `gradle.properties`, not here.
 */
export type BuildSettings = { 
/**
 * Automatically install and launch the app after a successful build.
 */
autoInstallOnBuild: boolean, 
/**
 * Last-used build variant name, persisted across sessions.
 */
buildVariant: string | null, 
/**
 * Last-used ADB device serial, persisted across sessions.
 */
selectedDevice: string | null, };
