// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One APK a successful build wrote, as listed in AGP's `output-metadata.json`.
 */
export type BuiltApk = { 
/**
 * Gradle path of the application module (`:app`; `:` for the root project).
 */
module: string, 
/**
 * The variant AGP names in `output-metadata.json` (`debug`, `paidRelease`).
 */
variant: string, 
/**
 * The variant's application ID, `applicationIdSuffix` included.
 */
applicationId: string | null, versionCode: number | null, 
/**
 * SHA-256 of the APK, lowercase hex.
 */
sha256: string, bytes: number, 
/**
 * Relative to the Gradle root.
 */
path: string, };
