// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildLineKind } from "./BuildLineKind";

/**
 * A single parsed line of build output, streamed from Rust to the frontend.
 */
export type BuildLine = { kind: BuildLineKind, 
/**
 * Raw content of the line (may include ANSI escape codes).
 */
content: string, 
/**
 * Source file path for error/warning lines.
 */
file: string | null, 
/**
 * 1-based line number for error/warning lines.
 */
line: number | null, 
/**
 * 1-based column number for error/warning lines.
 */
col: number | null, };
