// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build system settings: auto-deploy behaviour.
 * Gradle JVM/parallel/offline flags are configured in Android Studio / `gradle.properties`, not here.
 */
export type BuildSettings = { 
/**
 * Automatically install and launch the app after a successful build.
 */
autoInstallOnBuild: boolean, };
