// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";
import type { BuildError } from "./BuildError";
import type { BuildStatus } from "./BuildStatus";
import type { LaunchTiming } from "./LaunchTiming";

/**
 * A record of a past build kept in the build history ring-buffer.
 */
export type BuildRecord = { id: number, task: string, status: BuildStatus, errors: Array<BuildError>, startedAt: string, 
/**
 * Absolute path of the project root at the time the build ran.
 * Used to scope history to the currently active project.
 */
projectRoot: string | null, 
/**
 * Who started the build; `None` in records written before this was kept.
 */
origin: BuildActor | null, 
/**
 * Who cancelled the build, when it was cancelled.
 */
cancelledBy: BuildActor | null, 
/**
 * How long the app took to launch when Run App installed this build's APK.
 */
launch: LaunchTiming | null, };
