// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SHA-256 of one build file.
 */
export type BuildFileHash = { 
/**
 * Relative to the Gradle root (`gradle/libs.versions.toml`).
 */
path: string, 
/**
 * Lowercase hex.
 */
sha256: string, };
