// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildError } from "./BuildError";
import type { BuildStatus } from "./BuildStatus";

/**
 * A record of a past build kept in the build history ring-buffer.
 */
export type BuildRecord = { id: number, task: string, status: BuildStatus, errors: Array<BuildError>, startedAt: string, projectRoot: string | null, };
