// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildErrorSeverity } from "./BuildErrorSeverity";

/**
 * A structured build error or warning with an optional location reference.
 */
export type BuildError = { message: string, 
/**
 * Source file path, if known (None for dependency/configuration errors).
 */
file: string | null, 
/**
 * 1-based line number, if known.
 */
line: number | null, col: number | null, severity: BuildErrorSeverity, };
