// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildResult } from "./BuildResult";

/**
 * Current status of the build system.
 */
export type BuildStatus = { "state": "idle" } | { "state": "running", task: string, started_at: string, } | { "state": "success" } & BuildResult | { "state": "failed" } & BuildResult | { "state": "cancelled" };
