// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build system settings: auto-deploy behaviour.
 * Gradle JVM/parallel/offline flags are configured in Android Studio / `gradle.properties`, not here.
 */
export type BuildSettings = { 
/**
 * Automatically install and launch the app after a successful build.
 */
autoInstallOnBuild: boolean, 
/**
 * When true, the build log panel follows new output (scrolls to end) until paused.
 */
autoScrollBuildLog: boolean, 
/**
 * Days to keep build log files in ~/.keynobi/build-logs/ (default: 7).
 */
buildLogRetentionDays: number, 
/**
 * Max total size of ~/.keynobi/build-logs/ in MB before size-based rotation (default: 100).
 */
buildLogMaxFolderMb: number, };
