// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of a single line of build output.
 */
export type BuildLineKind = "output" | "error" | "warning" | "taskStart" | "taskEnd" | "summary";
