// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildErrorSeverity } from "./BuildErrorSeverity";

/**
 * A structured build error or warning with a location reference.
 */
export type BuildError = { message: string, file: string, line: number, col: number | null, severity: BuildErrorSeverity, };
