// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceEdit } from "./WorkspaceEdit";

export type CodeAction = { title: string, kind: string | null, isPreferred: boolean, edit: WorkspaceEdit | null, };
