// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionItemKind } from "./CompletionItemKind";

export type CompletionItem = { label: string, kind: CompletionItemKind, detail: string | null, insertText: string | null, sortText: string | null, filterText: string | null, };
