// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change of the logcat stream reading the session's device.
 */
export type DebugSessionLogcatChange = { serial: string, 
/**
 * Why the stream stopped, for `logcatStopped`.
 */
reason: string | null, };
