// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSession } from "./DebugSession";
import type { DebugSessionEvent } from "./DebugSessionEvent";

/**
 * A session and its most recent events, for the session view.
 */
export type DebugSessionDetail = { session: DebugSession, 
/**
 * Oldest first; at most `MAX_EVENTS_RETURNED`, the newest.
 */
events: Array<DebugSessionEvent>, 
/**
 * Whether older events were left out.
 */
eventsTruncated: boolean, };
