// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionCloseReason } from "./DebugSessionCloseReason";
import type { DebugSessionCounts } from "./DebugSessionCounts";
import type { DebugSessionDevice } from "./DebugSessionDevice";
import type { DebugSessionRecorder } from "./DebugSessionRecorder";

/**
 * A session as `index.json` lists it: what the list view shows.
 */
export type DebugSessionSummary = { id: string, projectRoot: string | null, package: string, device: DebugSessionDevice, buildId: number | null, module: string | null, variant: string | null, versionCode: number | null, apkSha256: string | null, 
/**
 * SHA-256 of each R8 mapping of the installed APK.
 */
mappingSha256s: Array<string>, openedAt: string, closedAt: string | null, closeReason: DebugSessionCloseReason | null, recordedBy: DebugSessionRecorder, kept: boolean, counts: DebugSessionCounts, lastEventAt: string, eventCount: number, droppedEvents: number, bytes: number, };
