// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactionCount } from "./RedactionCount";
import type { SessionExportOmission } from "./SessionExportOmission";

/**
 * Where an imported session came from.
 */
export type DebugSessionImport = { 
/**
 * The bundle's file name, without its folder.
 */
fileName: string, 
/**
 * When the bundle was exported, as its manifest says.
 */
exportedAt: string, importedAt: string, 
/**
 * The session's id where it was recorded.
 */
originalId: string, 
/**
 * The Keynobi version that exported it.
 */
keynobiVersion: string, 
/**
 * What the export, and then the import, left out, and why.
 */
omitted: Array<SessionExportOmission>, 
/**
 * The export's redaction rules, whether each was on, and what it replaced.
 */
redactions: Array<RedactionCount>, };
