// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attachment's content (`get_session_attachment`).
 */
export type DebugSessionAttachmentData = { 
/**
 * The attachment event's `seq`.
 */
seq: number, 
/**
 * `image/png`.
 */
mediaType: string, base64: string, };
