// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionAttachmentKind } from "./DebugSessionAttachmentKind";

/**
 * A file attached to the session: `attachments/<name>`.
 */
export type DebugSessionAttachment = { kind: DebugSessionAttachmentKind, 
/**
 * `screenshot-<seq>.png`, named by the event's `seq`.
 */
name: string, bytes: number, 
/**
 * The image's size in pixels.
 */
width: number, height: number, 
/**
 * The device it shows.
 */
serial: string, };
