// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an exit record was matched to the session.
 */
export type DebugSessionExitMatch = "pid" | "processName" | "timeWindow";
