// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionAttribution } from "./DebugSessionAttribution";
import type { DebugSessionCaptureRef } from "./DebugSessionCaptureRef";

/**
 * A crash or ANR that logcat showed for the session's app.
 */
export type DebugSessionCrash = { serial: string, pid: number | null, 
/**
 * The exception (`java.lang.RuntimeException: boom`) or the ANR line.
 */
summary: string, 
/**
 * Hash of the crash's first log line, which with the device, package,
 * pid, and time identifies one crash seen by several processes.
 */
signature: string, 
/**
 * When the first line reached Keynobi (host clock).
 */
receivedAt: string, 
/**
 * The first line's time as logcat printed it (device local time, no year).
 */
deviceTime: string, attribution: DebugSessionAttribution, 
/**
 * `None` past `MAX_CAPTURES_PER_SESSION`, or when no line was left to keep.
 */
capture: DebugSessionCaptureRef | null, 
/**
 * Logcat lines dropped by the stream so far (a flood), when it was captured.
 */
droppedLines: number, };
