// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node of an attached UI hierarchy.
 */
export type DebugSessionHierarchyNode = { 
/**
 * 0 for a top-level node; a child is one deeper than its parent.
 */
depth: number, class: string, resourceId: string, text: string, contentDesc: string, 
/**
 * As UI Automator prints it: `[left,top][right,bottom]`.
 */
bounds: string, };
