// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The session's device went offline or came back.
 */
export type DebugSessionDeviceChange = { serial: string, };
