// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";
import type { DebugSessionApk } from "./DebugSessionApk";
import type { DebugSessionMapping } from "./DebugSessionMapping";

/**
 * The build that produced the installed APK: its history record's id and a
 * digest that outlives the record.
 */
export type DebugSessionBuild = { id: number, task: string, startedAt: string, origin: BuildActor | null, apk: DebugSessionApk, mappings: Array<DebugSessionMapping>, };
