// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchTiming } from "./LaunchTiming";

/**
 * An app launch (Run App, MCP `launch_app`, or `restart_app`).
 */
export type DebugSessionLaunch = { serial: string, 
/**
 * `None` when the launch method reported no timing.
 */
timing: LaunchTiming | null, 
/**
 * A force-stop and relaunch rather than a plain launch.
 */
restart: boolean, };
