// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an MCP tool changes things, as its annotations declare.
 */
export type DebugSessionToolKind = "write" | "destructive" | "openWorld";
