// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppExitRecord } from "./AppExitRecord";
import type { DebugSessionExitMatch } from "./DebugSessionExitMatch";

/**
 * A process exit Android recorded for the session's app (Android 11+).
 */
export type DebugSessionExit = { serial: string, 
/**
 * The exit time on the host clock, from the device's local time and UTC offset.
 */
exitedAt: string, matchedBy: DebugSessionExitMatch, record: AppExitRecord, };
