// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What reading a session's exit reasons found.
 */
export type DebugSessionExitRefresh = { 
/**
 * Exit events added to the session.
 */
added: number, 
/**
 * Why nothing could be read (Android 10 or older), when so.
 */
message: string | null, };
