// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionToolKind } from "./DebugSessionToolKind";

/**
 * An MCP tool call that acted on the session's device. Its arguments are
 * never recorded; the agent is the event's actor.
 */
export type DebugSessionAgentAction = { tool: string, kind: DebugSessionToolKind, 
/**
 * The tool succeeded.
 */
ok: boolean, durationMs: number, serial: string, };
