// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessedEntry } from "./ProcessedEntry";

/**
 * The log lines kept with a crash (`get_session_capture`).
 */
export type DebugSessionCapture = { 
/**
 * The crash event's `seq`.
 */
seq: number, 
/**
 * Oldest first, ending with the crash's own lines.
 */
entries: Array<ProcessedEntry>, 
/**
 * Older lines of the capture were left out by the requested limit.
 */
truncated: boolean, };
