// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionAttributionMethod } from "./DebugSessionAttributionMethod";

/**
 * Why a crash belongs to its session's build, and whether the device
 * confirmed it.
 */
export type DebugSessionAttribution = { method: DebugSessionAttributionMethod, 
/**
 * The device still ran Keynobi's install when the crash was recorded.
 */
verified: boolean, 
/**
 * What the device said, or why it was not asked or not believed.
 */
reason: string | null, };
