// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of Keynobi process opened the session.
 */
export type DebugSessionRecorder = "app" | "standalone";
