// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An R8 mapping of the installed APK, by content hash.
 */
export type DebugSessionMapping = { sha256: string, pgMapId: string | null, };
