// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionAttachmentKind } from "./DebugSessionAttachmentKind";

/**
 * A file attached to the session: `attachments/<name>`.
 */
export type DebugSessionAttachment = { kind: DebugSessionAttachmentKind, 
/**
 * `screenshot-<seq>.png` or `hierarchy-<seq>.json`, named by the
 * event's `seq`.
 */
name: string, bytes: number, 
/**
 * A screenshot's size in pixels.
 */
width?: number, height?: number, 
/**
 * A hierarchy's nodes.
 */
nodeCount?: number, 
/**
 * The device it shows.
 */
serial: string, };
