// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";

/**
 * The install that opened the session.
 */
export type DebugSessionInstall = { apkSha256: string, versionCode: number | null, installedAt: string, by: BuildActor, };
