// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";
import type { DebugSessionAgentAction } from "./DebugSessionAgentAction";
import type { DebugSessionBookmark } from "./DebugSessionBookmark";
import type { DebugSessionBuild } from "./DebugSessionBuild";
import type { DebugSessionCrash } from "./DebugSessionCrash";
import type { DebugSessionDeviceChange } from "./DebugSessionDeviceChange";
import type { DebugSessionExit } from "./DebugSessionExit";
import type { DebugSessionInstall } from "./DebugSessionInstall";
import type { DebugSessionLaunch } from "./DebugSessionLaunch";
import type { DebugSessionLogcatChange } from "./DebugSessionLogcatChange";
import type { LaunchTiming } from "./LaunchTiming";

/**
 * One line of `sessions/<id>/events.jsonl`.
 */
export type DebugSessionEvent = { 
/**
 * 1 for the session's first event.
 */
seq: number, 
/**
 * Host time (RFC 3339).
 */
at: string, 
/**
 * Who caused it, when known.
 */
actor: BuildActor | null, } & ({ "kind": "build", "data": DebugSessionBuild } | { "kind": "install", "data": DebugSessionInstall } | { "kind": "launch", "data": DebugSessionLaunch } | { "kind": "launchTiming", "data": LaunchTiming } | { "kind": "logcatReconnect", "data": DebugSessionLogcatChange } | { "kind": "logcatStopped", "data": DebugSessionLogcatChange } | { "kind": "logcatCleared", "data": DebugSessionLogcatChange } | { "kind": "deviceOffline", "data": DebugSessionDeviceChange } | { "kind": "deviceOnline", "data": DebugSessionDeviceChange } | { "kind": "bookmark", "data": DebugSessionBookmark } | { "kind": "crash", "data": DebugSessionCrash } | { "kind": "anr", "data": DebugSessionCrash } | { "kind": "exit", "data": DebugSessionExit } | { "kind": "agentAction", "data": DebugSessionAgentAction });
