// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionHierarchyNode } from "./DebugSessionHierarchyNode";

/**
 * An attached UI hierarchy (`attachments/hierarchy-<seq>.json`): its nodes
 * in pre-order, a parent before its children, each with its depth, so the
 * file reads without recursion.
 */
export type DebugSessionHierarchy = { 
/**
 * When it was captured, on the host clock.
 */
capturedAt: string, 
/**
 * The resumed activity, when the device said.
 */
foregroundActivity: string | null, 
/**
 * Whether nodes or text were cut to the caps.
 */
truncated: boolean, nodes: Array<DebugSessionHierarchyNode>, };
