// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an attachment holds.
 */
export type DebugSessionAttachmentKind = "screenshot" | "hierarchy";
