// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many events of each kind a session holds.
 */
export type DebugSessionCounts = { launches: number, crashes: number, anrs: number, exits: number, bookmarks: number, 
/**
 * Crashes and ANRs whose log lines were kept.
 */
captures: number, 
/**
 * MCP tool calls that acted on the session's device.
 */
agentActions: number, };
