// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The device a session's app was installed on. An emulator is identified by
 * its AVD name, a physical device by its serial.
 */
export type DebugSessionDevice = { serial: string, avdName: string | null, 
/**
 * For display only.
 */
model: string | null, };
