// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The log lines kept with a crash: `captures/crash-<seq>.jsonl`, named by
 * the crash event's `seq`.
 */
export type DebugSessionCaptureRef = { entries: number, bytes: number, 
/**
 * Lines around the crash were left out by the capture caps.
 */
truncated: boolean, };
