// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionAgentAction } from "./DebugSessionAgentAction";
import type { DebugSessionBookmark } from "./DebugSessionBookmark";
import type { DebugSessionBuild } from "./DebugSessionBuild";
import type { DebugSessionCrash } from "./DebugSessionCrash";
import type { DebugSessionDeviceChange } from "./DebugSessionDeviceChange";
import type { DebugSessionExit } from "./DebugSessionExit";
import type { DebugSessionInstall } from "./DebugSessionInstall";
import type { DebugSessionLaunch } from "./DebugSessionLaunch";
import type { DebugSessionLogcatChange } from "./DebugSessionLogcatChange";
import type { LaunchTiming } from "./LaunchTiming";

/**
 * What happened, by kind.
 */
export type DebugSessionEventData = { "kind": "build", "data": DebugSessionBuild } | { "kind": "install", "data": DebugSessionInstall } | { "kind": "launch", "data": DebugSessionLaunch } | { "kind": "launchTiming", "data": LaunchTiming } | { "kind": "logcatReconnect", "data": DebugSessionLogcatChange } | { "kind": "logcatStopped", "data": DebugSessionLogcatChange } | { "kind": "logcatCleared", "data": DebugSessionLogcatChange } | { "kind": "deviceOffline", "data": DebugSessionDeviceChange } | { "kind": "deviceOnline", "data": DebugSessionDeviceChange } | { "kind": "bookmark", "data": DebugSessionBookmark } | { "kind": "crash", "data": DebugSessionCrash } | { "kind": "anr", "data": DebugSessionCrash } | { "kind": "exit", "data": DebugSessionExit } | { "kind": "agentAction", "data": DebugSessionAgentAction };
