// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSessionBuild } from "./DebugSessionBuild";
import type { DebugSessionCloseReason } from "./DebugSessionCloseReason";
import type { DebugSessionCounts } from "./DebugSessionCounts";
import type { DebugSessionDevice } from "./DebugSessionDevice";
import type { DebugSessionInstall } from "./DebugSessionInstall";
import type { DebugSessionRecorder } from "./DebugSessionRecorder";

/**
 * A session's manifest, `sessions/<id>/session.json`.
 */
export type DebugSession = { schemaVersion: number, id: string, projectRoot: string | null, package: string, device: DebugSessionDevice, 
/**
 * `None` when no recorded build wrote the installed APK.
 */
build: DebugSessionBuild | null, 
/**
 * `None` for a session no Keynobi install opened.
 */
install: DebugSessionInstall | null, openedAt: string, closedAt: string | null, closeReason: DebugSessionCloseReason | null, recordedBy: DebugSessionRecorder, 
/**
 * Exempt from age pruning, and pins the session's R8 mappings.
 */
kept: boolean, counts: DebugSessionCounts, lastEventAt: string, eventCount: number, 
/**
 * Events not recorded because a cap was reached.
 */
droppedEvents: number, 
/**
 * Size of the session's event log.
 */
bytes: number, };
