// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a run of a configuration is (`deploy:phase`).
 */
export type DeployPhase = "building" | "installing" | "launching" | "done" | "failed" | "cancelled";
