// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildActor } from "./BuildActor";
import type { DeployPhase } from "./DeployPhase";
import type { RunDevice } from "./RunDevice";

/**
 * Payload of `deploy:phase`: a run of a configuration in the app's process
 * (the app's own, or an attached agent's) entered `phase`.
 */
export type DeployPhaseEvent = { phase: DeployPhase, 
/**
 * Who runs it: the app, or an attached agent.
 */
origin: BuildActor, 
/**
 * The configuration's name.
 */
name: string, 
/**
 * The plan in one line.
 */
plan: string, device: RunDevice, 
/**
 * The run's build history record, once the build is recorded.
 */
buildId: number | null, 
/**
 * What the run did since the previous phase, one log line each.
 */
steps: Array<string>, 
/**
 * Why it failed (`failed`).
 */
error: string | null, };
