// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployOutcome } from "./DeployOutcome";
import type { LaunchResult } from "./LaunchResult";
import type { ResolvedRun } from "./ResolvedRun";
import type { RunApk } from "./RunApk";
import type { RunDevice } from "./RunDevice";

/**
 * What a run of a configuration did (`run_run_configuration`).
 */
export type DeployResult = { 
/**
 * The plan it ran.
 */
run: ResolvedRun, outcome: DeployOutcome, 
/**
 * The build history record of its build.
 */
buildId: number | null, 
/**
 * The device it installed on.
 */
device: RunDevice, 
/**
 * The APK it installed.
 */
apk: RunApk | null, 
/**
 * SHA-256 of that APK; `None` when it could not be hashed.
 */
apkSha256: string | null, 
/**
 * The installed APK's package; `None` when it could not be read.
 */
package: string | null, 
/**
 * `None` when it did not launch: the launch is `none`, or the package is unknown.
 */
launch: LaunchResult | null, 
/**
 * The configuration's logcat filter; `None` applies `package:mine`.
 */
logcatFilter: string | null, };
