// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a run of a configuration ended.
 */
export type DeployOutcome = "done" | "buildFailed" | "cancelled";
