// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hardware device definition from `avdmanager list device`.
 */
export type DeviceDefinition = { 
/**
 * Identifier used with `avdmanager create avd -d "..."` (e.g. `"pixel_7"`).
 */
id: string, 
/**
 * Human-readable name (e.g. `"Pixel 7"`).
 */
name: string, 
/**
 * Manufacturer name (e.g. `"Google"`).
 */
manufacturer: string, };
