// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ADB connection state for a device.
 */
export type DeviceConnectionState = "online" | "offline" | "unauthorized" | "unknown";
