// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the device is physical hardware or an Android emulator.
 */
export type DeviceKind = "physical" | "emulator";
