// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceConnectionState } from "./DeviceConnectionState";
import type { DeviceKind } from "./DeviceKind";

/**
 * An Android device or emulator visible to ADB.
 */
export type Device = { 
/**
 * ADB transport serial (e.g. `emulator-5554`, `ZX1G22ABCD`).
 */
serial: string, 
/**
 * Human-readable device name (from `ro.product.name` or parsed model).
 */
name: string, 
/**
 * Device model string (from `ro.product.model`).
 */
model: string | null, deviceKind: DeviceKind, connectionState: DeviceConnectionState, 
/**
 * Android API level (from `ro.build.version.sdk`).
 */
apiLevel: number | null, 
/**
 * Android version string (from `ro.build.version.release`).
 */
androidVersion: string | null, };
