// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

/**
 * Payload of `device:list_changed`.
 */
export type DeviceListChangedEvent = { devices: Array<Device>, };
