// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";
import type { TextRange } from "./TextRange";

export type Diagnostic = { path: string, range: TextRange, severity: DiagnosticSeverity, message: string, source: string | null, code: string | null, };
