// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadProgress = { downloadedBytes: bigint, totalBytes: bigint | null, percent: number | null, };
