// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettings = { fontFamily: string, fontSize: number, tabSize: number, insertSpaces: boolean, wordWrap: boolean, lineNumbers: boolean, bracketMatching: boolean, highlightActiveLine: boolean, autoCloseBrackets: boolean, };
