// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level classification of a log entry inferred from its tag.
 */
export type EntryCategory = "general" | "network" | "lifecycle" | "performance" | "gc" | "database" | "security";
