// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilesSettings = { excludedDirs: Array<string>, excludedExtensions: Array<string>, maxFileSizeMb: number, };
