// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEventKind } from "./FileEventKind";

/**
 * Emitted via Tauri events when the file watcher detects a change.
 */
export type FileEvent = { kind: FileEventKind, path: string, newPath: string | null, };
