// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileKind } from "./FileKind";

/**
 * A node in the project file tree. Sent from Rust to the frontend via IPC.
 *
 * TypeScript binding is auto-generated by `ts-rs` into
 * `src/bindings/FileNode.ts`. **Do not** maintain a manual TypeScript
 * interface for this type — import from `@/bindings` instead.
 */
export type FileNode = { name: string, path: string, kind: FileKind, children: Array<FileNode> | null, extension: string | null, };
