// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextEdit } from "./TextEdit";

export type FileEdit = { path: string, edits: Array<TextEdit>, };
