// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MappingSnapshot } from "./MappingSnapshot";

/**
 * The APK Keynobi last installed on one device for one package, and the
 * build that produced it. Saved in `installed-builds.json` in the data
 * directory, so it outlives the build's history record.
 */
export type InstalledBuild = { 
/**
 * The adb serial the APK was installed on.
 */
serial: string, 
/**
 * The emulator's AVD name, when it reported one. Emulator serials are
 * reused, so an emulator is identified by this, not by its serial.
 */
avdName: string | null, 
/**
 * The device model, for display only.
 */
model: string | null, 
/**
 * The package the APK installs.
 */
package: string, 
/**
 * SHA-256 of the installed APK, lowercase hex.
 */
apkSha256: string, 
/**
 * The history record of the build that wrote this APK; `None` when no
 * recorded build did (for example an APK another tool built).
 */
buildId: number | null, versionCode: number | null, 
/**
 * The saved R8 mappings of the APK's module and variant, copied from the
 * build's record. Kept while this entry names them.
 */
mappings: Array<MappingSnapshot>, 
/**
 * RFC 3339.
 */
installedAt: string, };
