// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the JDK used for Gradle builds was found.
 */
export type JdkSource = "userGradleProperties" | "projectGradleProperties" | "settings" | "androidStudio" | "installedJdk";
