// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchTiming } from "./LaunchTiming";

/**
 * Payload of `build:launch_timing`: display times that arrived after
 * `launch_app_on_device` returned, now recorded on the build.
 */
export type LaunchTimingEvent = { 
/**
 * The build history record the launch belongs to.
 */
recordId: number, launch: LaunchTiming, };
