// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Android started an activity, as `am start -W` reports it (Android 10+).
 */
export type LaunchState = "cold" | "warm" | "hot" | "relaunch";
