// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchState } from "./LaunchState";

/**
 * How long an activity launch took, measured with `am start -W`.
 */
export type LaunchTiming = { 
/**
 * `TotalTime`: from the start request until the activity drew its first frame.
 */
totalMs: number, 
/**
 * `WaitTime`: how long `am start` waited, including its own overhead.
 */
waitMs: number | null, 
/**
 * `None` when the device did not report it (before Android 10, or `UNKNOWN`).
 */
launchState: LaunchState | null, 
/**
 * When the launch finished (RFC 3339).
 */
measuredAt: string, 
/**
 * ADB serial of the device the app launched on.
 */
serial: string, 
/**
 * For an emulator, its AVD name, which identifies it across serials.
 */
avdName: string | null, 
/**
 * Device model, for display.
 */
model: string | null, };
