// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchTiming } from "./LaunchTiming";

/**
 * Result of `launch_app_on_device`.
 */
export type LaunchResult = { 
/**
 * What `am start` (or its fallback) printed.
 */
output: string, 
/**
 * `None` when the launch method reports no timing (the monkey and intent fallbacks).
 */
timing: LaunchTiming | null, };
