// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetPreference } from "./TargetPreference";

/**
 * Machine-specific state of one run configuration, never shared.
 */
export type LocalRunState = { target: TargetPreference, 
/**
 * Serial of the device it last ran on.
 */
lastDevice: string | null, 
/**
 * SHA-256 of the shared configuration file the user last approved.
 */
approvedProjectFileSha256: string | null, };
