// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * IPC-serialisable version of a logcat filter, sent from frontend → Rust.
 * The service layer converts this to the internal `LogcatFilter` for matching.
 */
export type LogcatFilterSpec = { minLevel: string | null, tag: string | null, text: string | null, package: string | null, onlyCrashes: boolean, };
