// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminant for special log entries (process lifecycle separators).
 */
export type LogcatKind = "normal" | "processDied" | "processStarted";
