// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logcat settings.
 */
export type LogcatSettings = { 
/**
 * Automatically start logcat streaming when a device connects.
 */
autoStart: boolean, 
/**
 * Maximum lines the Logcat panel keeps in memory and requests per backfill.
 */
maxUiLines: number, 
/**
 * Maximum entries in the in-memory logcat ring before oldest lines are dropped.
 */
ringMaxEntries: number, };
