// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Running statistics for the current logcat session.
 * Maintained in O(1) per entry by the LogStore.
 */
export type LogStats = { totalIngested: bigint, 
/**
 * Counts indexed by `LogcatLevel::priority()` (0 = Verbose … 5 = Fatal, 6 = Unknown).
 */
countsByLevel: [bigint, bigint, bigint, bigint, bigint, bigint, bigint], crashCount: bigint, jsonCount: bigint, packagesSeen: number, 
/**
 * Percentage of the ring buffer currently in use (0.0 – 100.0).
 * Computed as `(current_len / configured_ring_capacity) * 100`.
 */
bufferUsagePct: number, 
/**
 * Current number of entries in the in-memory ring buffer (all lines stored;
 * independent of the active stream filter used for IPC).
 */
bufferEntryCount: bigint, };
