// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspStatusState } from "./LspStatusState";

export type LspStatus = { state: LspStatusState, message: string | null, };
