// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A copy of one R8 `mapping.txt` a build wrote, saved as
 * `mappings/<sha256>.txt` in the data directory.
 */
export type MappingSnapshot = { 
/**
 * Gradle path of the application module (`:app`; `:` for the root project).
 */
module: string, 
/**
 * The directory AGP wrote the mapping to, named after the variant
 * (`release`, `paidRelease`).
 */
variant: string, 
/**
 * SHA-256 of the mapping, lowercase hex. Names the saved copy.
 */
sha256: string, bytes: number, 
/**
 * The `# pg_map_id:` header, when the mapping has one.
 */
pgMapId: string | null, };
