// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the MCP activity log.
 */
export type McpActivityEntry = { 
/**
 * ISO 8601 UTC timestamp.
 */
timestamp: string, 
/**
 * Event category: `"tool_call"`, `"resource_read"`, `"prompt"`, or `"lifecycle"`.
 */
kind: string, 
/**
 * Tool name, resource URI, prompt name, or lifecycle event description.
 */
name: string, 
/**
 * Wall-clock duration in milliseconds (present for tool/resource/prompt events).
 */
durationMs: bigint | null, 
/**
 * `"ok"` or `"error"`.
 */
status: string, 
/**
 * Brief human-readable summary of the result or error.
 */
summary: string | null, };
