// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An MCP client attached to the running app.
 */
export type McpAttachedSession = { 
/**
 * Unique for the life of the app process.
 */
id: number, 
/**
 * PID of the `keynobi --mcp` process forwarding the client's stdio.
 */
pid: number | null, 
/**
 * The project the session is pinned to, or `None` when it follows the app.
 */
project: string | null, 
/**
 * ISO 8601 UTC time the session attached.
 */
connectedAt: string, 
/**
 * The MCP client's name, once it has initialized.
 */
clientName: string | null, };
