// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the MCP integration with one AI client.
 */
export type McpClientSetupStatus = { 
/**
 * Whether the client CLI was found (via PATH, common install paths, or login shell).
 */
clientFound: boolean, 
/**
 * Whether `keynobi` is registered in this MCP client for every folder.
 */
isConfigured: boolean, 
/**
 * The command that is currently registered (if any).
 */
configuredCommand: string | null, 
/**
 * Scope of the registration found (`user`, `local`, `project`, …), when
 * the client reports one. A `local` or `project` registration only works
 * in one folder, so it does not count as configured.
 */
configuredScope: string | null, 
/**
 * Full setup command the user can copy into a terminal, or `None` when
 * the app's location must not be registered (see `location_problem`).
 */
setupCommand: string | null, };
