// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAttachedSession } from "./McpAttachedSession";
import type { McpStandaloneServer } from "./McpStandaloneServer";

/**
 * Live MCP sessions: attached to the app, and standalone servers.
 */
export type McpServerStatus = { 
/**
 * Whether the app is accepting MCP sessions on its socket.
 */
listening: boolean, attached: Array<McpAttachedSession>, standalone: Array<McpStandaloneServer>, };
