// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpClientSetupStatus } from "./McpClientSetupStatus";

/**
 * Status of the MCP integration with supported AI clients.
 */
export type McpSetupStatus = {
  /**
   * The real absolute path to this application's binary.
   */
  exePath: string;
  /**
   * The binary path with `--mcp` flag.
   */
  setupCommand: string;
  /**
   * Claude Code setup and configuration status.
   */
  claude: McpClientSetupStatus;
  /**
   * Codex setup and configuration status.
   */
  codex: McpClientSetupStatus;
};
