// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings for the MCP (Model Context Protocol) server integration.
 */
export type McpSettings = { 
/**
 * Maximum seconds to wait for a Gradle build via the `run_gradle_task`
 * MCP tool before cancelling. Increase for very large projects.
 */
buildTimeoutSec: number, 
/**
 * Default number of logcat entries returned by `get_logcat_entries`
 * when the caller does not specify a `count` argument.
 */
logcatDefaultCount: number, 
/**
 * Default number of raw build log lines returned by `get_build_log`
 * when the caller does not specify a `lines` argument.
 */
buildLogDefaultLines: number, 
/**
 * Let MCP clients run Gradle tasks that publish, promote, upload, or
 * uninstall (`publish*`, `promote*`, `upload*`, `uninstall*`, ...). Off by default. Only the
 * Settings panel changes this; no MCP tool writes it.
 */
allowUnrestrictedGradle: boolean, };
