// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live status of the headless MCP server process.
 */
export type McpServerStatus = { 
/**
 * Whether the MCP server process appears to be running.
 */
alive: boolean, 
/**
 * PID of the server process, if a PID file exists.
 */
pid: number | null, };
