// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpClientSetupStatus } from "./McpClientSetupStatus";

/**
 * Status of the MCP integration with supported AI clients.
 */
export type McpSetupStatus = { 
/**
 * The real absolute path to this application's binary.
 */
exePath: string, 
/**
 * The binary path with `--mcp` flag, or `None` when `location_problem` is set.
 */
setupCommand: string | null, 
/**
 * Why the app's path must not be registered (it runs from a disk image
 * or a temporary App Translocation copy), phrased for the user.
 */
locationProblem: string | null, 
/**
 * Claude Code setup and configuration status.
 */
claude: McpClientSetupStatus, 
/**
 * Codex setup and configuration status.
 */
codex: McpClientSetupStatus, };
