// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `keynobi --mcp` process running with its own state, not shared with the app.
 */
export type McpStandaloneServer = { pid: number, 
/**
 * ISO 8601 UTC start time.
 */
startedAt: string, 
/**
 * The server's project, if it found one.
 */
project: string | null, 
/**
 * Why it could not attach to the app.
 */
reason: string, };
