// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the MCP integration with Claude Code.
 */
export type McpSetupStatus = { 
/**
 * The real absolute path to this application's binary.
 * Use this to build the `claude mcp add` command.
 */
exePath: string, 
/**
 * The full `--command` string ready to paste into a terminal.
 */
setupCommand: string, 
/**
 * Whether the `claude` CLI was found (via PATH or login shell).
 */
claudeFound: boolean, 
/**
 * Whether `android-companion` is already registered in Claude Code.
 */
isConfigured: boolean, 
/**
 * The command that is currently registered (if any).
 */
configuredCommand: string | null, };
