// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryCategory } from "./EntryCategory";
import type { LogcatKind } from "./LogcatKind";
import type { LogcatLevel } from "./LogcatLevel";

/**
 * A fully-processed logcat entry, suitable for IPC transfer to the frontend.
 *
 * This replaces the old `LogcatEntry`. All enrichment from the pipeline
 * (package resolution, crash grouping, JSON detection, category) is embedded
 * directly in this struct to minimise IPC overhead.
 */
export type ProcessedEntry = { id: bigint, timestamp: string, pid: number, tid: number, level: LogcatLevel, tag: string, message: string, package: string | null, kind: LogcatKind, isCrash: boolean, 
/**
 * Bitfield of `EntryFlags` constants. Check with `(flags & EntryFlags::CRASH) !== 0`.
 */
flags: number, 
/**
 * High-level category inferred from the tag (e.g. Network, Lifecycle).
 */
category: EntryCategory, 
/**
 * Groups consecutive lines belonging to the same crash/ANR stack trace.
 * All lines in a single crash share the same `crash_group_id`.
 */
crashGroupId: bigint | null, 
/**
 * Raw JSON string extracted from the message, if the message contains
 * valid JSON. The frontend parses this on-demand (only when the user
 * expands the row) to avoid IPC bloat.
 */
jsonBody: string | null, };
