// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A known Android project entry in the project registry.
 * Persisted inside `AppSettings.recent_projects`.
 */
export type ProjectEntry = { 
/**
 * Deterministic hex ID derived from the canonical project path.
 */
id: string, 
/**
 * Absolute path to the project root folder.
 */
path: string, 
/**
 * Display name (the folder's base name).
 */
name: string, 
/**
 * Detected Gradle root (ancestor containing `settings.gradle(.kts)`),
 * or `None` if not yet detected.
 */
gradleRoot: string | null, 
/**
 * ISO-8601 timestamp of the last time this project was opened.
 */
lastOpened: string, 
/**
 * Whether the user has pinned this project (pinned entries sort first).
 */
pinned: boolean, };
