// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App version information read from (and written back to) `app/build.gradle(.kts)`.
 */
export type ProjectAppInfo = { 
/**
 * The `applicationId` declared in the app module (read-only — editing it
 * would require a full Gradle sync and is out of scope).
 */
applicationId: string | null, 
/**
 * Human-readable version string (e.g. `"1.2.3"`).
 */
versionName: string | null, 
/**
 * Integer version code used by the Play Store.
 */
versionCode: bigint | null, };
