// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalRunState } from "./LocalRunState";
import type { RunConfiguration } from "./RunConfiguration";
import type { SharedRunConfigurationsFile } from "./SharedRunConfigurationsFile";

/**
 * A project's run configurations, as `list_run_configurations` returns them.
 */
export type ProjectRunConfigurations = { configurations: Array<RunConfiguration>, 
/**
 * Name of the active configuration; `None` until one is chosen.
 */
active: string | null, 
/**
 * Local state by configuration name.
 */
local: { [key in string]: LocalRunState }, 
/**
 * Names of the configurations read from the project's shared file.
 */
shared: Array<string>, 
/**
 * The project's shared file; `None` when the project has none.
 */
sharedFile: SharedRunConfigurationsFile | null, };
