// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalRunState } from "./LocalRunState";
import type { RunConfiguration } from "./RunConfiguration";

/**
 * A known Android project entry in the project registry.
 * Persisted inside `AppSettings.recent_projects`.
 */
export type ProjectEntry = { 
/**
 * Deterministic hex ID derived from the canonical project path.
 */
id: string, 
/**
 * Absolute path to the project root folder.
 */
path: string, 
/**
 * Display name — defaults to the folder base name but can be renamed.
 */
name: string, 
/**
 * Detected Gradle root (ancestor containing `settings.gradle(.kts)`),
 * or `None` if not yet detected.
 */
gradleRoot: string | null, 
/**
 * ISO-8601 timestamp of the last time this project was opened.
 */
lastOpened: string, 
/**
 * Whether the user has pinned this project (pinned entries sort first).
 */
pinned: boolean, 
/**
 * Last-used build variant for this project (e.g. `"debug"`).
 */
lastBuildVariant: string | null, 
/**
 * Last-used ADB device serial for this project.
 */
lastDevice: string | null, 
/**
 * Whether Keynobi may run this project's Gradle build scripts:
 * `Some(true)` trusted, `Some(false)` Safe Mode (declined or revoked),
 * `None` not asked yet. Always written, so an entry saved before this
 * field existed is the only kind that reads as missing, and it is trusted.
 */
trusted: boolean | null, 
/**
 * The project's run configurations. `None` until they are first read,
 * which creates them from the application modules and the fields above
 * (see `services::run_configurations`).
 */
runConfigurations?: Array<RunConfiguration>, 
/**
 * Machine-specific state of each run configuration, by name.
 */
runLocal?: { [key in string]: LocalRunState }, 
/**
 * Name of the active run configuration.
 */
activeRunConfiguration?: string, };
