// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalRunState } from "./LocalRunState";
import type { RunConfiguration } from "./RunConfiguration";

/**
 * A project's run configurations, as `list_run_configurations` returns them.
 */
export type ProjectRunConfigurations = { configurations: Array<RunConfiguration>, 
/**
 * Name of the active configuration; `None` until one is chosen.
 */
active: string | null, 
/**
 * Local state by configuration name.
 */
local: { [key in string]: LocalRunState }, };
