// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which rules to apply. Every rule is on unless turned off.
 */
export type RedactionRules = { emails: boolean, secrets: boolean, ipAddresses: boolean, paths: boolean, deviceSerials: boolean, };
