// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One kind of personal or secret data redaction replaces.
 */
export type RedactionRule = "emails" | "secrets" | "ipAddresses" | "paths" | "deviceSerials";
