// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactionRule } from "./RedactionRule";

/**
 * How many matches of one rule were replaced.
 */
export type RedactionCount = { rule: RedactionRule, enabled: boolean, count: number, };
