// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunDevice } from "./RunDevice";
import type { RunLaunch } from "./RunLaunch";

/**
 * A run configuration checked against the project and the connected devices:
 * what Run builds, where it installs, and what it launches
 * (`resolve_run_configuration`).
 */
export type ResolvedRun = { 
/**
 * The configuration's name.
 */
name: string, module: string, variant: string, 
/**
 * The Gradle task to build: the configuration's, else
 * `:<module>:assemble<Variant>`.
 */
task: string, launch: RunLaunch, logcatFilter: string | null, 
/**
 * The online device to install on; `None` for a build-only plan.
 */
device: RunDevice | null, 
/**
 * The plan in one line, for the build log.
 */
plan: string, };
