// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MappingMatch } from "./MappingMatch";
import type { MappingSnapshot } from "./MappingSnapshot";
import type { RetraceStatus } from "./RetraceStatus";

/**
 * A crash stack trace, deobfuscated or not, and why.
 */
export type RetraceOutcome = { status: RetraceStatus, 
/**
 * The deobfuscated trace when `status` is `retraced`; otherwise the
 * trace as logcat printed it.
 */
trace: string, 
/**
 * The build whose mapping was used, or was to be used.
 */
buildId: number | null, 
/**
 * The mapping used, or the one a check refused.
 */
mapping: MappingSnapshot | null, matchedBy: MappingMatch | null, 
/**
 * The device: its AVD name, else its serial.
 */
device: string | null, package: string | null, 
/**
 * Why the trace was not deobfuscated.
 */
reason: string | null, 
/**
 * One line naming the mapping and how it was matched, or the reason.
 */
summary: string, };
