// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The APK Run App installs for one application module and variant.
 */
export type RunApk = { 
/**
 * Absolute path inside the application module's build outputs.
 */
path: string, 
/**
 * The build history record that lists this APK: the run's own, or, when
 * the run wrote none (Gradle found it up to date), the newest build that
 * wrote the same bytes. `None` when no kept build wrote it.
 */
buildId: number | null, 
/**
 * Whether the run's own build wrote it.
 */
fromThisBuild: boolean, };
