// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunLaunch } from "./RunLaunch";

/**
 * What Run builds and launches for one application module and variant.
 *
 * Portable: it holds no paths, serials, or environment, so it can be shared
 * with a project. Machine-specific state is in [`LocalRunState`].
 */
export type RunConfiguration = { 
/**
 * Unique per project.
 */
name: string, 
/**
 * Gradle path of an application module (`:app`; `:` for the root project).
 */
module: string, 
/**
 * AGP variant name (`debug`, `freeRelease`).
 */
variant: string, 
/**
 * The Gradle task to build; `None` for `:<module>:assemble<Variant>`.
 */
task: string | null, launch: RunLaunch, 
/**
 * Logcat query applied after launch, in the query bar's syntax.
 */
logcatFilter: string | null, };
