// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The device a run installs on.
 */
export type RunDevice = { serial: string, 
/**
 * The AVD name, else the model, else the serial.
 */
label: string, };
