// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Run starts after installing the APK.
 */
export type RunLaunch = { "kind": "default" } | { "kind": "activity", name: string, } | { "kind": "deepLink", uri: string, } | { "kind": "none" };
