// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single line of progress from an `sdkmanager` download.
 */
export type SdkDownloadProgress = { 
/**
 * Progress percentage 0–100, or `None` if indeterminate.
 */
percent: number | null, 
/**
 * Raw status line from sdkmanager (e.g. "Downloading...").
 */
message: string, 
/**
 * Whether the download has finished (success or failure).
 */
done: boolean, 
/**
 * Whether the download ended in an error.
 */
error: boolean, };
