// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchMatch = { line: number, col: number, endCol: number, lineContent: string, contextBefore: Array<string>, contextAfter: Array<string>, };
