// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchOptions = { regex: boolean, caseSensitive: boolean, wholeWord: boolean, includePattern: string | null, excludePattern: string | null, };
