// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactionCount } from "./RedactionCount";
import type { SessionExportOmission } from "./SessionExportOmission";

/**
 * A debug session saved as a bundle (`export_debug_session`).
 */
export type SessionExportResult = { 
/**
 * Where the bundle was saved, as chosen in the save dialog.
 */
path: string, bytes: number, 
/**
 * The bundle's files, in order.
 */
entries: Array<string>, 
/**
 * Matches each redaction rule replaced.
 */
redactions: Array<RedactionCount>, omitted: Array<SessionExportOmission>, };
