// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Debug session retention (`~/.keynobi/sessions/`).
 */
export type SessionSettings = { 
/**
 * Days to keep a session after its last event (default: 14; 0 disables).
 * Kept sessions are exempt.
 */
retentionDays: number, 
/**
 * Max total size of ~/.keynobi/sessions/ in MB before the oldest
 * sessions are removed (default: 200).
 */
maxFolderMb: number, };
