// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactionRules } from "./RedactionRules";

/**
 * What to put in an exported debug session.
 */
export type SessionExportOptions = { 
/**
 * The redaction rules to apply; all on by default.
 */
redaction: RedactionRules, 
/**
 * The log lines kept with each crash and ANR.
 */
includeCrashLogs: boolean, };
