// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something an exported bundle leaves out, and why.
 */
export type SessionExportOmission = { item: string, reason: string, };
