// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configuration of the shared file that is not offered.
 */
export type SharedRunConfigurationProblem = { 
/**
 * Its name, when the file gives one.
 */
name: string | null, message: string, };
