// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedRunConfigurationProblem } from "./SharedRunConfigurationProblem";

/**
 * The project's shared run configuration file
 * (`<gradle root>/.keynobi/run-configurations.json`), as last read.
 */
export type SharedRunConfigurationsFile = { 
/**
 * Path relative to the Gradle root.
 */
path: string, 
/**
 * SHA-256 of the file's bytes; `None` when it could not be read.
 */
sha256: string | null, 
/**
 * Why none of the file's configurations are offered.
 */
error: string | null, 
/**
 * Configurations of the file that are not offered, and why.
 */
problems: Array<SharedRunConfigurationProblem>, };
