// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterInfo } from "./ParameterInfo";

export type SignatureInfo = { label: string, documentation: string | null, parameters: Array<ParameterInfo>, };
