// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of running system-level health probes from Rust.
 * Frontend-observable store checks (LSP status, project open, settings) are
 * computed in TypeScript from existing stores; only checks that require
 * process execution or filesystem introspection are done here.
 */
export type SystemHealthReport = { 
/**
 * Whether `java -version` exits successfully.
 */
javaExecutableFound: boolean, 
/**
 * First line of `java -version` stderr output, e.g. `openjdk version "17.0.8" …`
 */
javaVersion: string | null, 
/**
 * The Java binary that was probed.
 */
javaBinUsed: string, 
/**
 * Whether the Android SDK path has recognisable SDK structure.
 */
androidSdkValid: boolean, 
/**
 * Whether `gradlew` exists at the project root.
 */
gradleWrapperFound: boolean, 
/**
 * Whether the LSP system directory (`~/.androidide/lsp-system/`) is writable.
 */
lspSystemDirOk: boolean, 
/**
 * Free disk space in the `~/.androidide` directory, in megabytes.
 * `None` when the measurement is unavailable on this platform.
 */
diskFreeMb: number | null, };
