// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of running system-level health probes from Rust.
 * Frontend-observable store checks (LSP status, project open, settings) are
 * computed in TypeScript from existing stores; only checks that require
 * process execution or filesystem introspection are done here.
 */
export type SystemHealthReport = { 
/**
 * Whether `java -version` exits successfully.
 */
javaExecutableFound: boolean, 
/**
 * First line of `java -version` stderr output, e.g. `openjdk version "17.0.8" …`
 */
javaVersion: string | null, 
/**
 * The Java binary that was probed.
 */
javaBinUsed: string, 
/**
 * Whether the Android SDK path has recognisable SDK structure.
 */
androidSdkValid: boolean, 
/**
 * Whether `adb` was found in `$ANDROID_HOME/platform-tools/` or on PATH.
 */
adbFound: boolean, 
/**
 * First line of `adb version` output.
 */
adbVersion: string | null, 
/**
 * Whether the Android emulator binary was found in `$ANDROID_HOME/emulator/`.
 */
emulatorFound: boolean, 
/**
 * Whether `gradlew` exists at the project root.
 */
gradleWrapperFound: boolean, 
/**
 * Whether the `.androidide` app directory is writable.
 */
lspSystemDirOk: boolean, 
/**
 * Whether the `studio` command is available on PATH (Android Studio CLI).
 */
studioCommandFound: boolean, };
