// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An installed Android system image available for AVD creation.
 */
export type SystemImageInfo = { 
/**
 * SDK ID used with `avdmanager create avd -k "..."` (e.g. `"system-images;android-35;google_apis;arm64-v8a"`).
 */
sdkId: string, 
/**
 * Android API level.
 */
apiLevel: number, 
/**
 * Image variant (e.g. `"google_apis"`, `"google_apis_playstore"`, `"default"`).
 */
variant: string, 
/**
 * CPU ABI (e.g. `"arm64-v8a"`, `"x86_64"`).
 */
abi: string, 
/**
 * Human-friendly label (e.g. `"Android 15 (Google APIs) · arm64-v8a"`).
 */
displayName: string, };
