// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which device Run installs on.
 */
export type TargetPreference = { "kind": "ask" } | { "kind": "serial", serial: string, } | { "kind": "avd", name: string, } | { "kind": "lastUsed" };
