// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Telemetry / crash-reporting settings.
 */
export type TelemetrySettings = {
  /**
   * Whether to send anonymous crash reports to help improve the app.
   * Default: false — user must opt in.
   */
  enabled: boolean;
};
