// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiLayoutContext } from "./UiLayoutContext";
import type { UiNode } from "./UiNode";

/**
 * Result of dumping and parsing the current screen hierarchy from a device.
 */
export type UiHierarchySnapshot = { 
/**
 * RFC3339 timestamp when the dump was taken (host clock).
 */
capturedAt: string, truncated: boolean, warnings: Array<string>, root: UiNode, 
/**
 * SHA-256 hex of interactive-relevant fields (for "did the screen change?").
 */
screenHash: string, interactiveCount: number, 
/**
 * Best-effort resumed activity line from `dumpsys activity`, if detected.
 */
foregroundActivity: string | null, 
/**
 * Capped `dumpsys window` / `dumpsys display` / `wm size` / `wm density` excerpts.
 */
layoutContext: UiLayoutContext, 
/**
 * Exact `adb …` lines executed during this capture (for reproducing in a terminal).
 */
commandLog: Array<string>, 
/**
 * Base64-encoded PNG screenshot captured alongside the hierarchy dump (optional).
 * Captured via `adb exec-out screencap -p`. Omitted when capture fails or is skipped.
 */
screenshotB64: string | null, };
