// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capped excerpts from official `adb shell` probes (window / display / wm) to interpret bounds.
 */
export type UiLayoutContext = { 
/**
 * First bytes of `dumpsys window windows` (focus / window tokens).
 */
windowExcerpt?: string, 
/**
 * First bytes of `dumpsys display`.
 */
displayExcerpt?: string, 
/**
 * Output of `wm size`.
 */
wmSize?: string, 
/**
 * Output of `wm density`.
 */
wmDensity?: string, };
