// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node in the Android accessibility / UI Automator XML tree.
 */
export type UiNode = { class: string, resourceId: string, text: string, contentDesc: string, package: string, bounds: string, clickable: boolean, enabled: boolean, focusable: boolean, focused: boolean, scrollable: boolean, longClickable: boolean, password: boolean, checkable: boolean, checked: boolean, editable: boolean, 
/**
 * UI Automator `selected` (e.g. bottom navigation tab).
 */
selected: boolean, 
/**
 * True when `class` looks like a Compose container (heuristic).
 */
isComposeHeuristic: boolean, children: Array<UiNode>, };
