// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildVariant } from "./BuildVariant";

/**
 * The full list of variants discovered for the project.
 */
export type VariantList = { variants: Array<BuildVariant>, 
/**
 * Currently selected variant name.
 */
active: string | null, };
