// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * A single structured log entry emitted by any log source (LSP server,
 * build system, Logcat, etc.).  The `source` field identifies the origin
 * so multiple sources can share the same [`LogViewer`] component.
 */
export type LogEntry = { 
/**
 * Monotonically-increasing counter used as a stable React/SolidJS key.
 */
id: number, 
/**
 * RFC 3339 timestamp of when the entry was received by the host process.
 */
timestamp: string, level: LogLevel, 
/**
 * Identifies the log source, e.g. `"lsp:server"`, `"lsp:stderr"`,
 * `"logcat:MyTag"`, `"build"`.
 */
source: string, message: string, };
