use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// A node in the project file tree. Sent from Rust to the frontend via IPC.
///
/// TypeScript binding is auto-generated by `ts-rs` into
/// `src/bindings/FileNode.ts`. **Do not** maintain a manual TypeScript
/// interface for this type — import from `@/bindings` instead.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../src/bindings/")]
pub struct FileNode {
    pub name: String,
    pub path: String,
    pub kind: FileKind,
    pub children: Option<Vec<FileNode>>,
    pub extension: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export, export_to = "../../src/bindings/")]
pub enum FileKind {
    File,
    Directory,
}

/// Emitted via Tauri events when the file watcher detects a change.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../src/bindings/")]
pub struct FileEvent {
    pub kind: FileEventKind,
    pub path: String,
    pub new_path: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export, export_to = "../../src/bindings/")]
pub enum FileEventKind {
    Created,
    Modified,
    Deleted,
    Renamed,
}

// ── Serialization tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{json, Value};

    #[test]
    fn file_node_serializes_to_camel_case() {
        let node = FileNode {
            name: "Main.kt".into(),
            path: "/project/app/src/Main.kt".into(),
            kind: FileKind::File,
            children: None,
            extension: Some("kt".into()),
        };
        let json: Value = serde_json::to_value(&node).unwrap();

        assert_eq!(json["name"], "Main.kt");
        assert_eq!(json["path"], "/project/app/src/Main.kt");
        assert_eq!(json["kind"], "file");
        assert_eq!(json["children"], Value::Null);
        assert_eq!(json["extension"], "kt");
    }

    #[test]
    fn file_node_directory_with_children() {
        let dir = FileNode {
            name: "src".into(),
            path: "/project/src".into(),
            kind: FileKind::Directory,
            children: Some(vec![FileNode {
                name: "index.kt".into(),
                path: "/project/src/index.kt".into(),
                kind: FileKind::File,
                children: None,
                extension: Some("kt".into()),
            }]),
            extension: None,
        };
        let json: Value = serde_json::to_value(&dir).unwrap();

        assert_eq!(json["kind"], "directory");
        assert!(json["children"].is_array());
        assert_eq!(json["children"][0]["name"], "index.kt");
        assert_eq!(json["extension"], Value::Null);
    }

    #[test]
    fn file_node_round_trip() {
        let original = FileNode {
            name: "App.kt".into(),
            path: "/project/App.kt".into(),
            kind: FileKind::File,
            children: None,
            extension: Some("kt".into()),
        };
        let json_str = serde_json::to_string(&original).unwrap();
        let deserialized: FileNode = serde_json::from_str(&json_str).unwrap();
        assert_eq!(original, deserialized);
    }

    #[test]
    fn file_kind_serializes_as_lowercase() {
        assert_eq!(serde_json::to_value(FileKind::File).unwrap(), json!("file"));
        assert_eq!(
            serde_json::to_value(FileKind::Directory).unwrap(),
            json!("directory")
        );
    }

    #[test]
    fn file_event_serializes_correctly() {
        let event = FileEvent {
            kind: FileEventKind::Created,
            path: "/project/new.kt".into(),
            new_path: None,
        };
        let json: Value = serde_json::to_value(&event).unwrap();

        assert_eq!(json["kind"], "created");
        assert_eq!(json["path"], "/project/new.kt");
        assert_eq!(json["newPath"], Value::Null);
    }

    #[test]
    fn file_event_renamed_with_new_path() {
        let event = FileEvent {
            kind: FileEventKind::Renamed,
            path: "/project/old.kt".into(),
            new_path: Some("/project/new.kt".into()),
        };
        let json: Value = serde_json::to_value(&event).unwrap();

        assert_eq!(json["kind"], "renamed");
        assert_eq!(json["newPath"], "/project/new.kt");
    }

    #[test]
    fn file_event_round_trip() {
        let original = FileEvent {
            kind: FileEventKind::Modified,
            path: "/project/file.kt".into(),
            new_path: None,
        };
        let json_str = serde_json::to_string(&original).unwrap();
        let deserialized: FileEvent = serde_json::from_str(&json_str).unwrap();
        assert_eq!(original, deserialized);
    }

    #[test]
    fn file_event_kind_all_variants_serialize() {
        assert_eq!(
            serde_json::to_value(FileEventKind::Created).unwrap(),
            json!("created")
        );
        assert_eq!(
            serde_json::to_value(FileEventKind::Modified).unwrap(),
            json!("modified")
        );
        assert_eq!(
            serde_json::to_value(FileEventKind::Deleted).unwrap(),
            json!("deleted")
        );
        assert_eq!(
            serde_json::to_value(FileEventKind::Renamed).unwrap(),
            json!("renamed")
        );
    }
}
